### ISSUE TITLE
Conflict with Shoulder Surfing Reloaded

### ISSUE THREAD

**Issue by Bufhimat** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#111]
MC version 1.10.2 with forge 2477, ShoulderSurfing-1.12.2-1.6 and Valkyrien Warfare 0.9_pre_1, no other mods.
3rd person cursor from Should Surfing Reloaded is present but the camera is centered behind the avatar's head, and keybindings for that mod to move camera left/right and zoom in/out do not work.

**Comment by sscards55** [comment]
This could probably be solved by adding ship views as a separate view rather than readjusting the current views.

**Comment by Exopandora** [comment]
As the maintainer of Shoulder Surfing Reloaded i can say that the mixin for EntityRenderer overrides the code Shoulder Surfing tries to modify at runtime. Specifically /src/main/java/valkyrienwarfare/mixin/client/renderer/MixinEntityRenderer#orientCamera. Due to the different register numbers afer compilation Shoulder Surfing is no longer able to find the correct injection point.

**Comment by Rubyjunk** [comment]
Continued in #294
