### ISSUE TITLE
crash  when  Phisic infuser activate(latest jenkins vw 429)

### ISSUE THREAD

**Issue by zayats1** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#233]
https://pastebin.com/UBA5tPPB

**Comment by Rubyjunk** [comment]
Hi, it looks like this issue is obsolete and is fixed in the latest builds of the mod. Thanks for taking the time to report this issue.

With <3,
Valkyrien Warfare Team

---

**You may obtain the latest, bleeding-edge build of Valkyrien Warfare containing these features, bug fixes, and more at the CircleCI page**

1. Navigate to this URL: https://circleci.com/gh/ValkyrienWarfare/Valkyrien-Warfare-Revamped/tree/master
2. Click on the latest build number
3. Click on artifacts
4. Download the JAR file of the mod
