### ISSUE TITLE
Crash with better portals 0.2.3

### ISSUE THREAD

**Issue by Rickstery123** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#274]
Crashes while game is loading on launch with better portals (latest alpha version)
[crash-2019-07-25_12.22.50-client.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/3432659/crash-2019-07-25_12.22.50-client.txt)

**Comment by Rubyjunk** [comment]
likely will not get fixed for awhile but it will be noted.

**Comment by Rubyjunk** [comment]
conflicting classes:

https://github.com/Johni0702/BetterPortals/blob/master/src/view/java/de/johni0702/minecraft/view/impl/mixin/MixinEntityRenderer.java

https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/master/src/main/java/valkyrienwarfare/mixin/client/renderer/MixinEntityRenderer.java

**Comment by DaMatrix** [comment]
The crashing is fixed in https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/commit/f5b8e696a507f0101a61eefd2d3fabcbbc5f8b7f , however it'll need a lot more work to be able to be called "compatible".

**Comment by DaMatrix** [comment]
A major problem is when the ship goes through the portal, everything starts breaking horribly. This is most likely due to the fact that the ship blocks are stored in one dimension and not the other, which will require a huge amount of additional work to fix.

However, I had some ideas a long time ago about storing airships in a totally separate world and then injecting the chunks into whichever world they happen to be in at the time (using mixins and some chunk provider hackery). I believe this would work correctly, and am going to start working on it in a new branch soon.

**Comment by DaMatrix** [comment]
On second thought, a mechanism for dimension changing with ships seems **far** out of scope of this issue, so I'm closing it for now. Dimension changing will be discussed further in #319.
